### ISSUE TITLE
Support for Visual Studio 16.1.4

### ISSUE THREAD

**Issue by danoliver1** [Cestbienmoi/Xsd2Code2015Plus#1]
After the most recent Visual Studio 2019 update, the extension is no longer showing in Extension Manager in Visual Studio. Please can you update the compatibility? 
(Thank you for your top-notch contributions to the open-source community!)

**Comment by danoliver1** [comment]
Fix for this in pull request #2

**Comment by Cestbienmoi** [comment]
I released a new version.
